config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users
  resources :articles
  get 'pages/home'
  get 'pages/portfolio'
  get 'pages/about'
  get 'pages/contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        if @article.save
            redirect_to @article
        else
            render 'new'
        end
    end

    def show
        @article = Article.find(params[:id])
    end

    def edit
         @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
        
        if @article.update(article_params)
            redirect_to @article
        else
            render 'edit'
        end
    
    end
    
    def destroy
        @article = Article.find(params[:id])
        @article.destroy

        redirect_to pages_home_path
         
    end
    

    private

    def article_params
        params.require(:article).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @articles = Article.all
  end

  def portfolio
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<section class="section">
    <div class="container">
        <%= simple_form_for @article do |f| %>
            <div class="field">
                <div class="control">
                    <%= f.input :title, input_html: { class: "input"}, wrapper: false, label_html: { class: "label"}%>
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <%= f.input :body, input_html: { class: "textarea"}, wrapper: false, label_html: { class: "label"} %>
                </div>    
            </div>
        <%= f.button :submit, class: "button is-info is-outlined" %>
        <% end %>
    </div>
</section>

app/views/articles/edit.html.erb
<%= content_for :page_title, "Edit Article"%>

<%= render 'form' %>

app/views/articles/new.html.erb
<%= content_for :page_title, 'Create Article' %>

<%= render 'form' %>

app/views/articles/show.html.erb
<% content_for :page_title, @article.title %>

<section class="section">
    <div class="box has-background-grey-lighter">
        <div class="container has-text-centered ">
            <h2 class="title">
                <%= @article.title %>
            </h2>
            <p class="subtitle">
                <%= @article.body %>
            </p>
        </div>
        <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure!?"}, class: "button is-danger is-outlined" %>
    </div>
    
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <section class="hero is-primary is-medium">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item">
            <img src="https://images.app.goo.gl/5oxVBgYFCnVqNCtR9" alt="Logo">
          </a>
          <span class="navbar-burger burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
               <%= link_to 'Home', pages_home_path, class: "navbar-item"  %>
               <%= link_to 'About', pages_about_path, class: "navbar-item"  %>
               <%= link_to 'Contact', pages_contact_path, class: "navbar-item"  %>
               <%= link_to 'Portfolio', pages_portfolio_path, class: "navbar-item"  %>
            <span class="navbar-item">
                <span> <%= link_to 'Create Article', new_article_path, class: "button is-info is-outlined"%></span>
            </span>
          </div>
        </div>
      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title">
        <%= yield :page_title%>
      </h1>
    </div>
  </div>
</section>
   
 
<div>
  <%= yield%>
</div>
     
     
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :page_title, 'About' %>

app/views/pages/contact.html.erb
<% content_for :page_title, 'Contact' %>

app/views/pages/home.html.erb
<% content_for :page_title, 'Homepage' %>
<section class="section">
    <div class="container">
        <% @articles.each do |post|%>
            <div class="box has-text-centered">
                    <p class="title">
                        <%=link_to post.title, @article %>
                    </p>
                    <hr>
                    <p class="subtitle">
                        <%= post.body%>
                    </p>     
            </div>
        <% end %>
    </div>
</section>
       
.

app/views/pages/portfolio.html.erb
<% content_for :page_title, 'Portfolio' %>